# Generated by Django 3.2.3 on 2021-06-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=77, unique=True),
        ),
        migrations.AlterField(
            model_name='testament',
            name='name',
            field=models.CharField(max_length=77, unique=True),
        ),
    ]
