# Generated by Django 3.2.3 on 2021-06-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20210608_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testament',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
