# Generated by Django 3.2.3 on 2021-06-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=0)),
                ('book', models.CharField(max_length=77)),
                ('chapter', models.IntegerField(default=0)),
                ('verse', models.IntegerField(default=0)),
            ],
        ),
    ]
