# Generated by Django 3.2.3 on 2021-06-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0002_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
    ]
