# Generated by Django 3.2.3 on 2021-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0003_remove_answer_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_id',
            field=models.IntegerField(default=0),
        ),
    ]
