# Generated by Django 3.2.3 on 2021-06-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glossary', '0004_answer_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_id',
        ),
        migrations.AddField(
            model_name='answer',
            name='word',
            field=models.CharField(default=' ', max_length=77),
        ),
    ]
