

Abbreviations  = {  'OldT' : [ 
                        {'book': 'Genesis ', 'abrv': 'Gn'},
                        {'book': 'Exodus ', 'abrv': 'Ex'},
                        {'book': 'Leviticus ', 'abrv': 'Lv'},
                        {'book': 'Numbers ', 'abrv': 'Nm'},
                        {'book': 'Deuteronomy ', 'abrv': 'Dt'},
                        {'book': 'Joshua ', 'abrv': 'Jos'},
                        {'book': 'Judges ', 'abrv': 'Jgs'},
                        {'book': 'Ruth ', 'abrv': 'Ru'},
                        {'book': '1 Samuel ', 'abrv': '1 Sm'},
                        {'book': '2 Samuel ', 'abrv': '2 Sm'},
                        {'book': '1 Kings ', 'abrv': '1 Kgs'},
                        {'book': '2 Kings ', 'abrv': '2 Kgs'},
                        {'book': '1 Chronicles ', 'abrv': '1 Chr'},
                        {'book': '2 Chronicles ', 'abrv': '2 Chr'},
                        {'book': 'Ezra ', 'abrv': 'Ezr'},
                        {'book': 'Nehemiah ', 'abrv': 'Neh'},
                        {'book': 'Esther ', 'abrv': 'Est'},
                        {'book': 'Job ', 'abrv': 'Jb'},
                        {'book': 'Psalms ', 'abrv': 'Ps'},
                        {'book': 'Proverbs ', 'abrv': 'Prv'},
                        {'book': 'Ecclesiastes ', 'abrv': 'Eccl'},
                        {'book': 'Song of Solomon ', 'abrv': 'Sg'},
                        {'book': 'Isaiah ', 'abrv': 'Is'},
                        {'book': 'Jeremiah ', 'abrv': 'Jer'},
                        {'book': 'Lamentations ', 'abrv': 'Lam'},
                        {'book': 'Ezekiel ', 'abrv': 'Ezk'},
                        {'book': 'Daniel ', 'abrv': 'Dn'},
                        {'book': 'Hosea ', 'abrv': 'Hos'},
                        {'book': 'Joel ', 'abrv': 'Jl'},
                        {'book': 'Amos ', 'abrv': 'Am'},
                        {'book': 'Obadiah ', 'abrv': 'Ob'},
                        {'book': 'Jonah ', 'abrv': 'Jon'},
                        {'book': 'Micah ', 'abrv': 'Mi'},
                        {'book': 'Nahum ', 'abrv': 'Na'},
                        {'book': 'Habakkuk ', 'abrv': 'Hab'},
                        {'book': 'Zephaniah ', 'abrv': 'Zep'},
                        {'book': 'Haggai ', 'abrv': 'Hg'},
                        {'book': 'Zechariah ', 'abrv': 'Zec'},
                        {'book': 'Malachi ', 'abrv': 'Mal'}
                    ],
        'NewT':[   
                            {'book': 'Matthew ', 'abrv': 'Mt'},
                            {'book': 'Mark ', 'abrv': 'Mk'},
                            {'book': 'Luke ', 'abrv': 'Lk'},
                            {'book': 'John ', 'abrv': 'Jn'},
                            {'book': 'Acts ', 'abrv': 'Acts'},
                            {'book': 'Romans ', 'abrv': 'Rom'},
                            {'book': '1 Corinthians ', 'abrv': '1 Cor'},
                            {'book': '2 Corinthians ', 'abrv': '2 Cor'},
                            {'book': 'Galatians ', 'abrv': 'Gal'},
                            {'book': 'Ephesians ', 'abrv': 'Eph'},
                            {'book': 'Philippians ', 'abrv': 'Phil'},
                            {'book': 'Colossians ', 'abrv': 'Col'},
                            {'book': '1 Thessalonians ', 'abrv': '1 Thes'},
                            {'book': '2 Thessalonians ', 'abrv': '2 Thes'},
                            {'book': '1 Timothy ', 'abrv': '1 Tm'},
                            {'book': '2 Timothy ', 'abrv': '2 Tm'},
                            {'book': 'Titus ', 'abrv': 'Ti'},
                            {'book': 'Philemon ', 'abrv': 'Phlm'},
                            {'book': 'Hebrews ', 'abrv': 'Heb'},
                            {'book': 'James ', 'abrv': 'Jas'},
                            {'book': '1 Peter ', 'abrv': '1 Pt'},
                            {'book': '2 Peter ', 'abrv': '2 Pt'},
                            {'book': '1 John ', 'abrv': '1 Jn'},
                            {'book': '2 John ', 'abrv': '2 Jn'},
                            {'book': '3 John ', 'abrv': '3 Jn'},
                            {'book': 'Jude ', 'abrv': 'Jude'},
                            {'book': 'Revelation ', 'abrv': 'Rv'}
                ]
}
